// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjZ_LVZrIR25GesIGptR4eqnW2H_OVQYI',
    appId: '1:613277586109:web:62debecd227920ebbc5dd4',
    messagingSenderId: '613277586109',
    projectId: 'evolvix-5f20b',
    authDomain: 'evolvix-5f20b.firebaseapp.com',
    storageBucket: 'evolvix-5f20b.firebasestorage.app',
    measurementId: 'G-DRYQQFJER7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC9qOZhrW1JtxDdMRWCbawKSzI-8v4TJ0',
    appId: '1:613277586109:android:35f4b59655ae3476bc5dd4',
    messagingSenderId: '613277586109',
    projectId: 'evolvix-5f20b',
    storageBucket: 'evolvix-5f20b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2HYbjKGDD1JtAKoKrqIwylO6we03QzQA',
    appId: '1:613277586109:ios:b19ce4ed9433ab0fbc5dd4',
    messagingSenderId: '613277586109',
    projectId: 'evolvix-5f20b',
    storageBucket: 'evolvix-5f20b.firebasestorage.app',
    iosBundleId: 'com.example.evolvix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2HYbjKGDD1JtAKoKrqIwylO6we03QzQA',
    appId: '1:613277586109:ios:b19ce4ed9433ab0fbc5dd4',
    messagingSenderId: '613277586109',
    projectId: 'evolvix-5f20b',
    storageBucket: 'evolvix-5f20b.firebasestorage.app',
    iosBundleId: 'com.example.evolvix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjZ_LVZrIR25GesIGptR4eqnW2H_OVQYI',
    appId: '1:613277586109:web:a6ed983642ada038bc5dd4',
    messagingSenderId: '613277586109',
    projectId: 'evolvix-5f20b',
    authDomain: 'evolvix-5f20b.firebaseapp.com',
    storageBucket: 'evolvix-5f20b.firebasestorage.app',
    measurementId: 'G-RRFXVFYS5Y',
  );
}
